spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: conquer
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: false
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
